module.exports = {

    first_name: element(by.id('firstName')),
    last_name: element(by.id('lastName')),
    ID: element(by.id('knownAs')),
    select_box: element.all(by.css('[class="ccf-select-box-inner"]')),   
    house_number: element(by.id('houseNumber')),
    street_name: element(by.id('streetName')),
    city: element(by.id('townCity')),
    county: element(by.id('county')),
    postcode: element(by.id('postcode')),
    child_add_btn : element(by.css('[class="menu-icon icon-child icon-2x"]')),
    first_name_value : ('First Name'),
    last_name_value : ('Last Name'),
    knownAs_value : ('init'),
    //select_box_inner: element.all(by.css('[class="ccf-select-box-inner"]')),
    house_number_value : ('666'),
    street_name_value : ('Satan Ave'),
    city_value : ('udontwantoknow'),
    county_value : ('county'),
    postcode_value : ('M1M1'),
    calendar_field : element.all(by.css('[class="ccf-input mat-input-element mat-form-field-autofill-control cdk-text-field-autofill-monitored"]')),
    start_date : ('11/11/2018'),
    end_date : ('11/11/2020'),
    option_value : ('.ccf-option-value'),
    school_field : ('school'),
    allergies_field : ('something'),
    notes_field : ('work'),
    next_button : ('.ccf-btn-inner'),
    image_upload_button: element(by.css('[class="ccf-input-icon icon-image"]')),
}